/*
 * Americano scheduling for an exact-fit roster.
 *
 * Partners come from the circle method: fix one player, rotate the rest, and read the pairs off
 * opposite ends of the circle. For a roster of n players that produces n-1 rounds in which every
 * player partners every other player exactly once — so partner variety is a property of the
 * construction rather than something a search has to be talked into. Past round n-1 the rotation
 * simply comes round again, which is why a partnership only ever repeats once nobody has an
 * unplayed partner left.
 *
 * Because each round's pairs depend only on the round number, fairness holds at every prefix
 * (decision #6) and an already-generated round is reproduced identically rather than disturbed.
 *
 * The one genuine choice left is which pair faces which — that is a small deterministic search
 * that minimises opponent repeats, with ties broken by enumeration order rather than by chance.
 * The player rotation is seeded from the session id, so two sessions do not open with the same
 * fixture list, and the same session always schedules identically.
 *
 * Known limitation of this first version: because partners are a function of the round number,
 * a session whose played rounds were *not* generated by this engine is scheduled without regard
 * to the partnerships those rounds already used. The history-aware search arrives with bench
 * rotation in a later ticket.
 *
 * Everything below is private: only `generateRemaining` is exported from the library.
 */
import { matchId } from './create-session';
import { deepFreeze } from './freeze';
import type { Match, PlayerId, Round, Session } from './model';
import { PairTally } from './pair-tally';
import { assertSessionShape } from './session-shape';

type Pair = readonly [PlayerId, PlayerId];

export function generateRemaining(session: Session): Session {
  assertSessionShape(session);

  const order = seededOrder(session);
  const opponentCounts = new PairTally();
  const rounds: Round[] = [];

  for (const round of session.rounds) {
    // A round that has already been generated is carried through untouched: regeneration
    // never rewrites play that has happened.
    const filled: Round =
      round.matches.length > 0
        ? copyRound(round)
        : { ...round, matches: buildMatches(session, order, round.number, opponentCounts) };

    recordOpponents(filled, opponentCounts);
    rounds.push(filled);
  }

  // Copies all the way down, so freezing the session we return never reaches back and freezes
  // arrays the caller still owns.
  return deepFreeze({
    ...session,
    roster: session.roster.map((entry) => ({ ...entry })),
    rounds,
  });
}

/**
 * The roster ids rotated by an offset derived from the session id, so the schedule is seeded
 * from session data rather than from a clock or a random source.
 */
function seededOrder(session: Session): PlayerId[] {
  const ids = session.roster.map((entry) => entry.id);
  const offset = fnv1a(session.id) % ids.length;

  return [...ids.slice(offset), ...ids.slice(0, offset)];
}

function buildMatches(
  session: Session,
  order: readonly PlayerId[],
  roundNumber: number,
  opponentCounts: PairTally,
): Match[] {
  const pairs = partnersForRound(order, roundNumber);

  return assignCourts(pairs, opponentCounts).map(([sideAIndex, sideBIndex], index) => ({
    id: matchId(session.id, roundNumber, index + 1),
    courtNumber: index + 1,
    sideA: pairs[sideAIndex],
    sideB: pairs[sideBIndex],
  }));
}

/** A round carried through untouched, copied so the returned session shares nothing with the input. */
function copyRound(round: Round): Round {
  return {
    ...round,
    matches: round.matches.map((match) => ({
      ...match,
      sideA: [match.sideA[0], match.sideA[1]] as const,
      sideB: [match.sideB[0], match.sideB[1]] as const,
    })),
  };
}

/**
 * The circle method: player at the end of the order stays put while the rest rotate, and pairs
 * are read off opposite ends of the rotating circle. Round `n-1 + 1` starts the rotation again.
 */
function partnersForRound(order: readonly PlayerId[], roundNumber: number): Pair[] {
  const playerCount = order.length;
  const rotating = playerCount - 1;
  const step = (roundNumber - 1) % rotating;

  const pairs: Pair[] = [[order[rotating], order[step]]];
  for (let offset = 1; offset < playerCount / 2; offset++) {
    pairs.push([order[(step + offset) % rotating], order[(step - offset + rotating) % rotating]]);
  }

  return pairs;
}

/**
 * Split the round's pairs into matches — two pairs per court — minimising how often the same
 * players face each other. Ties go to the first arrangement found, which makes the result a
 * function of the round's pairs and the history alone.
 */
function assignCourts(pairs: readonly Pair[], opponentCounts: PairTally): [number, number][] {
  const taken = pairs.map(() => false);
  const current: [number, number][] = [];
  let best: [number, number][] = [];
  let bestCost = Number.POSITIVE_INFINITY;

  const search = (cost: number): void => {
    if (cost >= bestCost) {
      return;
    }

    const next = taken.indexOf(false);
    if (next === -1) {
      bestCost = cost;
      best = [...current];
      return;
    }

    taken[next] = true;
    for (let other = next + 1; other < pairs.length; other++) {
      if (taken[other]) {
        continue;
      }

      taken[other] = true;
      current.push([next, other]);
      search(cost + opponentCost(pairs[next], pairs[other], opponentCounts));
      current.pop();
      taken[other] = false;
    }
    taken[next] = false;
  };

  search(0);

  return best;
}

function opponentCost(sideA: Pair, sideB: Pair, opponentCounts: PairTally): number {
  let cost = 0;
  for (const a of sideA) {
    for (const b of sideB) {
      cost += opponentCounts.count(a, b);
    }
  }

  return cost;
}

function recordOpponents(round: Round, opponentCounts: PairTally): void {
  for (const match of round.matches) {
    for (const a of match.sideA) {
      for (const b of match.sideB) {
        opponentCounts.increment(a, b);
      }
    }
  }
}

/** FNV-1a: a small, stable string hash. Same string in, same number out, on every run. */
function fnv1a(value: string): number {
  let hash = 0x811c9dc5;
  for (let index = 0; index < value.length; index++) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }

  return hash;
}
