#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# The project id is the only value this wizard captures. It is not a secret — it
# ends up in .firebaserc, which is committed. .env.firebase exists only so that a
# re-run can offer it back as a default; .gitignore already covers .env.*
ENV_FILE=".env.firebase"

if [[ ! -f angular.json ]]; then
  printf '\n  Run this from the padel-tournament-hub repo root.\n\n' >&2
  exit 1
fi

banner "Padel Tournament Hub · Firebase Hosting (issue #57)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "The Firebase CLI"
say "Everything after this point needs the firebase CLI on your PATH."
if command -v firebase >/dev/null 2>&1; then
  note "found: $(firebase --version 2>/dev/null | head -n1)"
else
  warn "firebase-tools is not installed."
  if confirm "Install it now with 'npm install -g firebase-tools'?"; then
    npm install -g firebase-tools
  else
    SKIPPED+=("install firebase-tools: npm install -g firebase-tools")
    warn "carrying on, but the later stages will fail without it"
  fi
fi
say ""
say "Now sign the CLI in to the Google account that should own this project."
note "This opens a browser. Use the account you want this recoverable from — it is"
note "the only owner there will be."
if command -v firebase >/dev/null 2>&1; then
  if firebase login:list 2>/dev/null | grep -q "@"; then
    note "already signed in"
    if confirm "Sign in as a different account?"; then firebase login --reauth; fi
  else
    firebase login
  fi
fi
pause "Signed in. Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the Firebase project"
say "Create the project in the console, then paste its id back here."
open_url "https://console.firebase.google.com/"
step "Click 'Create a project' (or 'Add project')."
step "Name it: padel-tournament-hub"
step "Firebase suggests a globally-unique project id under the name — something"
step "  like padel-tournament-hub-4f2a1. That id becomes your <id>.web.app address."
step "Google Analytics: turn it OFF. Decision #10 keeps this app free of tracking,"
step "  and Analytics is the one switch that would quietly undo that."
step "Wait for 'Your new project is ready', then Continue."
say ""
ask FIREBASE_PROJECT_ID "Paste the project id (not the display name):"
if [[ -z "$FIREBASE_PROJECT_ID" ]]; then
  warn "no project id given; cannot continue"
  exit 1
fi
write_env FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"
if command -v firebase >/dev/null 2>&1; then
  if firebase projects:list 2>/dev/null | grep -q "$FIREBASE_PROJECT_ID"; then
    printf '  %s✓%s the CLI can see %s\n' "$GREEN" "$RESET" "$FIREBASE_PROJECT_ID"
  else
    warn "the CLI cannot see a project with that id."
    warn "Check it under console → Project settings → Project ID before continuing."
    pause "Enter to continue anyway."
  fi
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Firestore location · the one irreversible click"
warn "A project's Firestore location can NEVER be changed afterwards."
warn "Not by support, not by a setting. The only fix is a new project."
say ""
say "Nothing reads Firestore until issue #58, but the location is fixed when the"
say "database is created — so it is set now, while the project is still empty and"
say "cheap to throw away if this goes wrong."
say ""
say "The value to choose is:  europe-central2  (Warsaw)"
note "Closest region to Vilnius, ~400 km. Chosen over europe-north1 (Finland) and"
note "over the eur3 multi-region, whose availability guarantees are aimed at"
note "businesses that lose money during an outage. See ADR-0025."
say ""
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID/firestore"
step "Click 'Create database'."
step "Database ID: leave it as (default)."
step "Location: choose europe-central2 (Warsaw) from the Region list."
step "  Do NOT accept a pre-selected nam5 / us-central default."
step "Rules: choose 'Start in production mode' (locked down)."
step "  The real rules arrive with issue #58; an open test-mode database on a"
step "  30-day timer is not a thing to leave lying around in the meantime."
step "Click Create and wait for it to provision."
say ""
if ! confirm "Does the console now show the database in europe-central2?"; then
  warn "Stop here and fix it before going further."
  warn "If it provisioned in the wrong region, delete the project and start again"
  warn "from stage 2 — that really is the cheapest fix, and right now it is free."
  exit 1
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Point the repo at the project"
say "Writing .firebaserc so 'firebase deploy' knows where to go."
{
  printf '{\n'
  printf '  "projects": {\n'
  printf '    "default": "%s"\n' "$FIREBASE_PROJECT_ID"
  printf '  }\n'
  printf '}\n'
} > .firebaserc
printf '  %s✓ wrote%s .firebaserc → default: %s\n' "$GREEN" "$RESET" "$FIREBASE_PROJECT_ID"
note ".firebaserc gets committed; .env.firebase does not (.gitignore covers .env.*)."
say ""
note "A 'dev' alias belongs here when issue #58 lands — sharing one Firestore"
note "between a preview channel and a live evening is the thing you would regret."
pause "Enter to continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Build and deploy"
if [[ ! -f firebase.json ]]; then
  warn "There is no firebase.json in this repo yet."
  say ""
  say "That file is the code half of issue #57, and it has not been written:"
  note "  - hosting.public → dist/padel-app/browser"
  note "  - an SPA rewrite of ** to /index.html"
  note "  - the web app manifest, and the 192 / 512 / maskable icons"
  say ""
  say "The account, the project and the region are all set up — that was the half"
  say "only you could do. Hand issue #57 to an agent for the config, then re-run"
  say "this wizard and it will carry on from here."
  SKIPPED+=("firebase.json + manifest + icons (issue #57, code half)")
  SKIPPED+=("first deploy: re-run this wizard once firebase.json exists")
  finish
  exit 0
fi
say "Building padel-engine and padel-app, then deploying Hosting only."
note "Spark allows 360 MB of Hosting transfer a day — roughly 700 cold loads at a"
note "500 KB bundle. That, not Firestore reads, is this project's real cap."
say ""
if confirm "Run 'npm run build' now?"; then
  npm run build
fi
if [[ ! -d dist/padel-app/browser ]]; then
  warn "dist/padel-app/browser is missing — the build did not produce what Hosting expects."
  SKIPPED+=("first deploy: build output missing")
  finish
  exit 1
fi
say ""
if confirm "Deploy to https://$FIREBASE_PROJECT_ID.web.app now?"; then
  firebase deploy --only hosting
else
  SKIPPED+=("firebase deploy --only hosting")
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Put it on a phone"
say "The reason to deploy this early is the phone, not the URL: iOS installs a PWA"
say "only from real HTTPS, which is the one thing a localhost build cannot give"
say "you (decision #22)."
say ""
open_url "https://$FIREBASE_PROJECT_ID.web.app"
step "Open that same URL on your iPhone, in Safari — Chrome on iOS cannot install."
step "Share → Add to Home Screen."
step "Check the icon: it should be the mark, not a screenshot of the page."
step "  A screenshot means the manifest icons are not being served."
step "Launch it from the home screen — it should open with no address bar."
say ""
note "There is deliberately no service worker yet, so it will not work offline and"
note "every launch fetches fresh. That is step 4's job (decision #15), kept out on"
note "purpose while this URL is being redeployed daily."
say ""
if ! confirm "Did it install and launch standalone?"; then
  SKIPPED+=("iOS install check — worth its own issue if the manifest is at fault")
fi

finish
